Fix for missing custom classname on the frontend
darylldoyle/safe-svg pull request #130
Opened 2023-06-21 13:09 UTC by bmarshall511

### Description of the Change

Fixes the missing custom classname on the frontend. It was being applied in the editor, but not when rendering on the front.

Closes #126 

### How to test the Change

1. Insert Safe SVG Icon block
2. Apply a custom class to block
3. Save page / post
4. View source in the frontend to verify the class has been applied

### Changelog Entry

> Fixed - Fix for missing custom classname on the frontend

### Credits

Props @bmarshall511 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

2023-06-29 08:53 UTC, Sidsector9 requested changes

2023-06-29 08:53 UTC, Sidsector9 commented on includes/blocks/safe-svg/register.php
> +			isset( $attributes['className'] ) ? ' ' . $attributes['className'] : '',
Thanks for the PR @bmarshall511 

I noticed that none of the outputs are escaped. This line in particular can be escaped using `esc_attr()`.
I was able to inject JavaScript through the CSS classes field.

Add this string as the CSS class `"onclick="alert('hello')"` as shown in the image:

<img width="281" alt="Screenshot 2023-06-29 at 2 19 46 PM" src="https://github.com/10up/safe-svg/assets/17757960/4940c70b-3b3a-4afb-92c2-3399ea806c22">

Visit the frontend and click the SVG, observe the `alert()`.

https://github.com/10up/safe-svg/assets/17757960/bfa8b8bb-6ab9-48b8-9f4a-ce83e2174476


Let me know your thoughts on this.

2023-06-29 12:37 UTC, bmarshall511 commented on includes/blocks/safe-svg/register.php
> +			isset( $attributes['className'] ) ? ' ' . $attributes['className'] : '',
@Sidsector9 My mistake & thanks for catching that! I've updated the code accordingly.

2023-07-03 19:33 UTC, dkotter approved these changes

2023-07-03 19:39 UTC, merged