Fix/only allow svg when uploading
darylldoyle/safe-svg pull request #228
Opened 2024-09-26 16:12 UTC by darylldoyle

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability
> Developer - Non-functional update

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [ ] All new and existing tests pass.

2024-09-26 18:40 UTC, dkotter requested changes
So this doesn't work for me, I always get the `Sorry, you are not allowed to upload this file type` error message.

I think what's happening is there's an earlier mime check that fires before the `wp_handle_upload_prefilter` filter and since we aren't adding the svg mime until that filter runs, things no longer work.

To test, I'm in the Media Library admin page, with the Grid View on. If I drag and drop an svg image, I get the above error.

2024-09-26 18:44 UTC, dkotter commented
I was curious on how our E2E tests were passing here when I couldn't get things to work. Looking into that, the `uploadMedia` command we use goes to `/wp-admin/media-new.php` and uploads from there. If I go to that page directly, I can upload svgs just fine but as mentioned above, I can't upload svgs from the main Media Library screen, which is interesting

2024-09-30 10:49 UTC, darylldoyle commented
Thanks for flagging @dkotter! I too could replicate on the media grid view. I've resolved this and added additional tests for that. I also had to allow uploads from a few additional contexts, because otherwise you could _only_ upload SVGs from the media pages. We _might_ want to add some additional tests for these, but I don't have time at the moment.

2024-10-07 15:18 UTC, dkotter approved these changes

2024-10-16 01:27 UTC, merged